### ISSUE TITLE
Improvements to Readme

### ISSUE THREAD

**Issue by yanniedog** [mik3y/airdash#12]
`# Read AIS data from the local serial port
DATA_SOURCES=ais-serial:///dev/ttyS0?baud=57600`

There should only be // not ///

Also, is it possible to somehow automatically detect the baud rate the serial port is set to?

**Comment by mik3y** [comment]
> There should only be // not ///

While a little ugly, the three slashes are correct. You can think of it as two parts: `ais-serial://`, similar to `http://`; and `/dev/ttyS0` as the second part, similar to `www.google.com`.

It _is_ a little unusual looking though, I'll add a call out.

> Also, is it possible to somehow automatically detect the baud rate the serial port is set to?

Good question! If you leave off the `?baud=..` parameter, it should just leave the baud rate alone. I'll call this out as well.

**Comment by yanniedog** [comment]
Thanks mik3y. I'm sure you're totally aware of the process, but FYI I set the baud rate on this port via the command `$ stty –F /dev/ttyS0 38400` during the initial setup of this AIS receiver

**Comment by yanniedog** [comment]
The readme states `AIS (aircraft)` in two locations. Should be `AIS (boats)`

**Comment by mik3y** [comment]
Thanks! Made these updates in f21bd0b.

**Comment by yanniedog** [comment]
Thanks mik3y
